version: '3'

services:
    jenkins:
        image: jenkins/jenkins:jdk11
        container_name: jenkins
        ports:
        - "8880:8080"
        - "50000:50000"
        volumes: 
        - ../volumes/jenkins:/var/jenkins_home

    ubuntu:
        container_name: ubuntu
        build: 
          context: ../dockerfiles/slave
        volumes: 
        - /var/run/docker.sock:/var/run/socker.sock
        command: java -jar agent.jar -jnlpUrl http://192.168.44.44:8880/computer/Slave/slave-agent.jnlp -secret 4576e23bab55a574d97e689e41f78786783a8ed4c245f4e0d82f9448d0b45c3e -workDir "/home/"
        depends_on:
        - jenkins
        networks: 
        - docker_network        

    artifactory:
        image: docker.bintray.io/jfrog/artifactory-oss:latest
        container_name: artifactory
        volumes: 
        - ../volumes/artifactory:/var/opt/jfrog/artifactory
        ports:
        - "8081:8081" # wystaw port na swiat / wystawia samego na siebie
        - "8082:8082"
        networks:
        - docker_network

    selenium_hub:
        image: selenium/hub
        container_name: seleniumhub
        ports:
        - "4444:4444"
        networks:
        - docker_network
        #pozostal tylko NODE, podejemy 2 zmienne srtodowiskowe HUB Host i HUB Port

    selenium_firefox:
        image: selenium/node-firefox
        container_name: firefox
        depends_on:
        - selenium_hub
        environment:
        - HUB_HOST=selenium
        - HUB_PORT=4444
        networks:
        - docker_network   

networks:
    docker_network:
        driver: bridge
    

